image: node:latest

services:
  - mysql:latest

cache:
  paths:
    - node_modules/

lint:
  script:
    - npm install
    - npm run lint

staging:
  type: deploy
  image: ruby:latest
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=novelshive --api-key=$HEROKU_KEY
  only:
    - dev
    - master
